### ISSUE TITLE
Installation check error: Expected to be a int64 tensor but is a int32.

### ISSUE THREAD

**Issue by prkasamit02** [google-research/bleurt#9]
Hi ,

I have installed BLEURT and  running the test script to test installation, getting below error. Paths to directory seems to be correct .
-----------
python -m bleurt.score \
  -candidate_file=bleurt/test_data/candidates \
  -reference_file=bleurt/test_data/references \
  -bleurt_checkpoint=bleurt/test_checkpoint \
  -scores_file=scores

----------

INFO:tensorflow:BLEURT initialized.
I0630 08:28:46.424506 24396 score.py:151] BLEURT initialized.
INFO:tensorflow:Computing BLEURT scores...
I0630 08:28:46.424506 24396 score.py:305] Computing BLEURT scores...
Traceback (most recent call last):
  File "C:\Users\amit.prakash\Anaconda3\envs\tf\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\amit.prakash\Anaconda3\envs\tf\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\amit.prakash\Anaconda3\envs\tf\lib\site-packages\bleurt\score.py", line 344, in <module>
    tf.app.run()
  File "C:\Users\amit.prakash\Anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\amit.prakash\Anaconda3\envs\tf\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\amit.prakash\Anaconda3\envs\tf\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "C:\Users\amit.prakash\Anaconda3\envs\tf\lib\site-packages\bleurt\score.py", line 339, in main
    FLAGS.bleurt_checkpoint)
  File "C:\Users\amit.prakash\Anaconda3\envs\tf\lib\site-packages\bleurt\score.py", line 321, in score_files
    _consume_buffer()
  File "C:\Users\amit.prakash\Anaconda3\envs\tf\lib\site-packages\bleurt\score.py", line 300, in _consume_buffer
    scores = scorer.score(ref_buffer, cand_buffer, FLAGS.bleurt_batch_size)
  File "C:\Users\amit.prakash\Anaconda3\envs\tf\lib\site-packages\bleurt\score.py", line 186, in score
    predict_out = self.predict_fn(tf_input)
  File "C:\Users\amit.prakash\Anaconda3\envs\tf\lib\site-packages\bleurt\score.py", line 70, in _predict_fn
    segment_ids=tf.constant(input_dict["segment_ids"])
  File "C:\Users\amit.prakash\Anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\eager\function.py", line 1551, in __call__
    return self._call_impl(args, kwargs)
  File "C:\Users\amit.prakash\Anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\eager\function.py", line 1591, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "C:\Users\amit.prakash\Anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\eager\function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "C:\Users\amit.prakash\Anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\eager\function.py", line 545, in call
    ctx=ctx)
  File "C:\Users\amit.prakash\Anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\eager\execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute __inference_pruned_1485 as input #0(zero-based) was expected to be a int64 tensor but is a int32 tensor [Op:__inference_pruned_1485]

Thanks,
Amit

**Comment by nguyenquangminh** [comment]
Hi,  @prkasamit02 I met the same issue as you. I think you could add "dtype" option to "tf.contant(...." parts. I added this option like below and the problem solved.
![image](https://user-images.githubusercontent.com/17470900/87293185-264c7800-c52c-11ea-97af-90335d76d2a8.png)

**Comment by MirunaClinciu** [comment]
Hi,

I'm having the same issue and the aforementioned solution didn't work.

 tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute __inference_pruned_7448 as input #0(zero-based) was expected to be a int64 tensor but is a int32 tensor [Op:__inference_pruned_7448]

**Comment by tsellam** [comment]
Hi, is this still an issue?

**Comment by versipellis** [comment]
Hi @tsellam, are there plans to merge in #44 to resolve this bug?

**Comment by swarooprm** [comment]
same issue.

**Comment by BramVanroy** [comment]
Unfortunately, Still experiencing the same issue. As OP, I'm also on Windows. Trace:

```
Traceback (most recent call last):
  File "<userpath>site-packages\bleurt\score.py", line 215, in score
    predict_out = self._predictor.predict(tf_input)
  File "<userpath>site-packages\bleurt\score.py", line 71, in predict
    input_dict["segment_ids"]))["predictions"].numpy()
  File "<userpath>site-packages\tensorflow\python\eager\function.py", line 1604, in __call__
    return self._call_impl(args, kwargs)
  File "<userpath>site-packages\tensorflow\python\eager\wrap_function.py", line 244, in _call_impl
    args, kwargs, cancellation_manager)
  File "<userpath>site-packages\tensorflow\python\eager\function.py", line 1622, in _call_impl
    return self._call_with_flat_signature(args, kwargs, cancellation_manager)
  File "<userpath>site-packages\tensorflow\python\eager\function.py", line 1671, in _call_with_flat_signature
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "<userpath>site-packages\tensorflow\python\eager\function.py", line 1863, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "<userpath>site-packages\tensorflow\python\eager\function.py", line 504, in call
    ctx=ctx)
  File "<userpath>site-packages\tensorflow\python\eager\execute.py", line 55, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute __inference_pruned_6256 as input #0(zero-based) was expected to be a int64 tensor but is a int32 tensor [Op:__inference_pruned_6256]
```

**Comment by BramVanroy** [comment]
@tsellam  please re-open and/or pull https://github.com/google-research/bleurt/pull/44

**Comment by afamera** [comment]
I am new to Bleurt and I am struggling with the same issue. Has this been resolved? I am trying to use the Python API

**Comment by tsellam** [comment]
Hi, thanks for pointing out. Is the issue resolved? Thanks!
